[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.19.4",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "pyshp>=2.3.1",
    "streamlit>=1.41.1",
    "streamlit-folium>=0.24.0",
]
